spring:
  application:
    name: library
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: library
    password: library_app
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: create-drop